Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -29,6 +29,7 @@ jobs:
           AWS_DEFAULT_REGION: us-east-1
         run: |
           IMAGE_TAG=$(date +%Y%m%d%H%M%S)
+          cp -R libs/common apps/api/libs/common
           docker build -t api-api:${IMAGE_TAG} -f apps/api/Dockerfile .
           docker tag api-api:${IMAGE_TAG} 730335666258.dkr.ecr.us-east-1.amazonaws.com/api-api:${IMAGE_TAG}
           docker push 730335666258.dkr.ecr.us-east-1.amazonaws.com/api-api:${IMAGE_TAG}
@@ -54,6 +55,10 @@ jobs:
           AWS_DEFAULT_REGION: us-east-1
         run: |
           IMAGE_TAG=$(date +%Y%m%d%H%M%S)
+          cp -R libs/common apps/auth/libs/common
+          if [ ! -d "apps/auth" ]; then
+            echo "Error: apps/auth directory does not exist!" && exit 1
+          fi
           docker build -t api-auth:${IMAGE_TAG} -f apps/auth/Dockerfile .
           docker tag api-auth:${IMAGE_TAG} 730335666258.dkr.ecr.us-east-1.amazonaws.com/api-auth:${IMAGE_TAG}
           docker push 730335666258.dkr.ecr.us-east-1.amazonaws.com/api-auth:${IMAGE_TAG}
